from github import Github
from config import GITHUB_TOKEN, GITHUB_REPO


def create_pull_request(branch_name):

    g = Github(GITHUB_TOKEN)

    repo = g.get_repo(GITHUB_REPO)

    base_branch = "main"   # force base branch

    try:
        pr = repo.create_pull(
            title="Automated API Migration",
            body="This PR was automatically generated by the Proactive Maintenance Agent.",
            head=branch_name,
            base=base_branch
        )

        print("Pull Request Created:")
        print(pr.html_url)
        return pr.html_url

    except Exception as e:
        print("PR creation skipped or already exists.")
        print(e)
        return None